// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_DN_lh-n3kUMIV0ax-S9Uqfdqh5ODc7Q',
    appId: '1:767598817853:web:9102cdbe80f8fe315d3054',
    messagingSenderId: '767598817853',
    projectId: 'notely-c6e52',
    authDomain: 'notely-c6e52.firebaseapp.com',
    storageBucket: 'notely-c6e52.firebasestorage.app',
    measurementId: 'G-6ZPQ97HEQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALSCScpWZLza1xRY901D5a59T9YkruBoU',
    appId: '1:767598817853:android:99a0950dc44573045d3054',
    messagingSenderId: '767598817853',
    projectId: 'notely-c6e52',
    storageBucket: 'notely-c6e52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM5-7wp-8NTnrxi18H0_Xv1RHb4XWueRY',
    appId: '1:767598817853:ios:2613093d43c552f15d3054',
    messagingSenderId: '767598817853',
    projectId: 'notely-c6e52',
    storageBucket: 'notely-c6e52.firebasestorage.app',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM5-7wp-8NTnrxi18H0_Xv1RHb4XWueRY',
    appId: '1:767598817853:ios:2613093d43c552f15d3054',
    messagingSenderId: '767598817853',
    projectId: 'notely-c6e52',
    storageBucket: 'notely-c6e52.firebasestorage.app',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_DN_lh-n3kUMIV0ax-S9Uqfdqh5ODc7Q',
    appId: '1:767598817853:web:1f0a8ff671a9399c5d3054',
    messagingSenderId: '767598817853',
    projectId: 'notely-c6e52',
    authDomain: 'notely-c6e52.firebaseapp.com',
    storageBucket: 'notely-c6e52.firebasestorage.app',
    measurementId: 'G-898TBFKJYQ',
  );
}
